stages:
  - build
  - test
  - deploy

variables:
  BUILD_DIR: build
  CONFIGURATION: Release

before_script:
  - apt-get update -y
  - apt-get install -y cmake g++ git libgtest-dev build-essential
  # Build GoogleTest static libs (required because libgtest-dev installs source only)
  - cd /usr/src/gtest
  - cmake .
  - make
  - cp libgtest.a libgtest_main.a /usr/lib/ || echo "No .a files found, skipping"
  - cd $CI_PROJECT_DIR

build:
  stage: build
  script:
    - rm -rf $BUILD_DIR
    - mkdir -p $BUILD_DIR
    - cd $BUILD_DIR
    - cmake .. -DCMAKE_BUILD_TYPE=$CONFIGURATION
    - cmake --build .
  artifacts:
    paths:
      - $BUILD_DIR
    expire_in: 1 hour

test:
  stage: test
  dependencies:
    - build
  script:
    - cd $BUILD_DIR
    - ./test_clearorder --gtest_output=xml:test-clearorder-results.xml
    - ./test_emptyorder --gtest_output=xml:test-emptyorder-results.xml
    - ./test_ids --gtest_output=xml:test-ids-results.xml
    - ./test_largequantity --gtest_output=xml:test-largequantity-results.xml
    - ./test_menu --gtest_output=xml:test-menu-results.xml
    - ./test_orderitem --gtest_output=xml:test-orderitem-results.xml
    - ./test_setname --gtest_output=xml:test-setname-results.xml
  artifacts:
    when: always
    reports:
      junit:
        - $BUILD_DIR/test-clearorder-results.xml
        - $BUILD_DIR/test-emptyorder-results.xml
        - $BUILD_DIR/test-ids-results.xml
        - $BUILD_DIR/test-largequantity-results.xml
        - $BUILD_DIR/test-menu-results.xml
        - $BUILD_DIR/test-orderitem-results.xml
        - $BUILD_DIR/test-setname-results.xml
    paths:
      - $BUILD_DIR/*.xml

deploy:
  stage: deploy
  dependencies:
    - build
  script:
    - echo "Deploying application..."
    - mkdir -p deploy_output
    - cp $BUILD_DIR/test_clearorder deploy_output/ || echo "test_clearorder not found"
    - cp $BUILD_DIR/test_emptyorder deploy_output/ || echo "test_emptyorder not found"
    - cp $BUILD_DIR/test_ids deploy_output/ || echo "test_ids not found"
    - cp $BUILD_DIR/test_largequantity deploy_output/ || echo "test_largequantity not found"
    - cp $BUILD_DIR/test_menu deploy_output/ || echo "test_menu not found"
    - cp $BUILD_DIR/test_orderitem deploy_output/ || echo "test_orderitem not found"
    - cp $BUILD_DIR/test_setname deploy_output/ || echo "test_setname not found"
    - ls deploy_output
  artifacts:
    paths:
      - deploy_output
    expire_in: 1 hour

