version: 2.1

executors:
  cxx-executor:
    docker:
      - image: cimg/base:stable
    working_directory: ~/repo

jobs:
  build:
    executor: cxx-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y cmake libgtest-dev build-essential
            cd /usr/src/gtest
            sudo cmake .
            sudo make
            sudo cp libgtest.a libgtest_main.a /usr/lib || echo "No .a files found, skipping"
      - run:
          name: Build project
          command: |
            rm -rf build
            mkdir build
            cd build
            cmake ..
            cmake --build .
      - persist_to_workspace:
          root: .
          paths:
            - build

  test:
    executor: cxx-executor
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: Run tests
          command: |
            cd /workspace/build
            ./tests --gtest_output=xml:/workspace/test_results.xml
      - store_test_results:
          path: /workspace
      - store_artifacts:
          path: /workspace/test_results.xml

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
