version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y cmake libgtest-dev build-essential
            cd /usr/src/gtest
            sudo cmake .
            sudo make
            sudo cp libgtest.a libgtest_main.a /usr/lib || echo "No .a files found, skipping"
      - run:
          name: Build project
          command: |
            rm -rf build
            mkdir build
            cd build
            cmake .. -DCMAKE_BUILD_TYPE=Release
            cmake --build .
            mkdir -p ../tests
            cp test_calculator ../tests/ || echo "test_calculator not found"
      - persist_to_workspace:
          root: .
          paths:
            - build
            - tests

  test:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run passing tests and generate XML reports
          command: |
            cd tests
            for test_exec in $(ls | grep -v -i fail); do
              chmod +x $test_exec
              ./$test_exec --gtest_output=xml:${test_exec}_results.xml || true
            done
      - store_test_results:
          path: tests
      - store_artifacts:
          path: tests

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
